### PR TITLE
Make percent, elapsed-time, remaining-time functions reusable from outside

### PR DESCRIPTION
**Pull request by olimsaidov**

### CODE REVIEW

**Comment by weavejester** [comment]
Can you provide a use case and explanation?

**Comment by olimsaidov** [comment]
I'm using this library in a worker that prints progress-bar on stdout and also pushes current progress and estimated remaining time to redis as int values.

**Comment by weavejester** [comment]
Thanks. This seems fine, but could you change the commit message to:

    Make some helper functions public

**Comment by olimsaidov** [comment]
@weavejester Commit message is changed.

**Pull request merged**
